### PR TITLE
Make `for` more generic

### PR DESCRIPTION
**Pull request by zlondrej**

### CODE REVIEW

**Review by Taneb — APPROVED** [review]
Does this break type inference for us anywhere?

**Review by theophile-scrive — APPROVED** [review]
Interesting, I would have expected that the difference between the `[b]` and `f (t b)` return types would anger some use-sites, but perhaps it's not used at all?

**Review by arybczak — CHANGES_REQUESTED** [review]
These functions are not equivalent, `for` from `Data.Traversable` is flipped `traverse`, our `for` is flipped `map`. It's better to remove `for` from `Prelude` if we don't use it anywhere. If we do use it, since this `for` is more polymorphic, it's possible that it will still typecheck, but have different behavior at runtime.

**Comment by zlondrej** [comment]
Oh crap, now I feel stupid.

I just wanted to make `for` more generic, and I went directly for `Traversable`'s `for`, without realizing that the mapping function actually produces `Applicative` result.

I should have done just `flip fmap` instead.

**Comment by zlondrej** [comment]
@arybczak Done: https://github.com/scrive/scrive-prelude/pull/15

**Review by arybczak — APPROVED** [review]

**Pull request merged**
